### ISSUE TITLE
help for install

### ISSUE THREAD

**Issue by FranJavier99** [lutris/docs#100]
Err:5 http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu kinetic Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Leyendo lista de paquetes... Hecho                      
E: El repositorio «http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu kinetic Release» no tiene un fichero de Publicación.

**Comment by crazyc4t** [comment]
Hola Fransisco! Que version de Ubuntu utilizas? el error que tienes puede ser por tu conexion de internet, te recomiendo leer esta documentación, probablemente te ayude https://github.com/lutris/docs/blob/master/WineDependencies.md.

Si nos pudieses decir que hiciste para llegar ese punto, que querías hacer en primer momento y que versión de ubuntu tienes sería perfecto para poderte ayudar.

**Comment by strycore** [comment]
Based on the date, I would say you were trying to use the PPA on a beta version of Ubuntu (kinetic kudu was released in Oct 2022)
Most of the time, PPAs do not  have packages for unreleased Ubuntu versions.
Also, Mesa in Ubuntu pre-releases should be fairly up to date so there is little need to update it with a PPA.
