### ISSUE TITLE
Dependancy download issue

### ISSUE THREAD

**Issue by GodsBadAssBlade** [lutris/docs#106]
godsbadassblade@pop-os:~$ sudo apt install libldap-2.4-2:i386  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libldap-2.4-2:i386
E: Couldn't find any package by glob 'libldap-2.4-2'

this is for the origin launcher

any suggestions?

**Comment by tannisroot** [comment]
just skip that package

**Comment by GodsBadAssBlade** [comment]
> just skip that package

I would but the exe is missing still(different issue i know but I think this would fix it)

**Comment by tannisroot** [comment]
it wouldn't. message me on discord if you want help with origin
