### ISSUE TITLE
I'm not able to install Blizzard Battlenet on PopOS 22.04

### ISSUE THREAD

**Issue by rodrigooomc83** [lutris/docs#114]
Despite creating the wine prefix, after downloading the install executable, the process gets stuck when it needs to download an update and gets stuck and doesn't advance the installation. The same happens when I try to install by overwatch script.

**Comment by gardotd426** [comment]
1. This is not the Lutris Application repo. This repo is just for docs. You don't report even *assumed* Lutris bugs here. 

2. More importantly, this is not a Lutris bug. It's universal, everyone has been hit by it, whether they're using Lutris, Bottles, or something more exotic. Battle.Net had an update that broke Linux compatibility. Filing a bug report with Lutris's *docs* page does nothing but waste their already **very** limited time. 
In the future, if you actually do find a bug with *Lutris*, you first go report it to the discord, and then depending on whether it's a real Lutris bug or not, you'll be told to file a bug report at https://github.com/lutris/lutris.

You'll notice that https://github.com/lutris/lutris/issues is obviously where this type of stuff would need to be sent, only in this case it's not a Lutris bug. So this issue just needs to be deleted
