### ISSUE TITLE
Origin game install directory

### ISSUE THREAD

**Issue by anfokaboom** [lutris/docs#122]
Hello
I respect the complexities involved with Origin in Linux but I thought I'd check none the less. When installing a game in Origin, I'm not sure how to identify exactly where that game will be installed. The options available to check or decide are a little limited. For example, I can't read the path shown in the text box, and the Change Location button takes me to an explorer dialogue that doesn't appear to work (link).

![origin](https://user-images.githubusercontent.com/79981132/206882960-00e6464a-877c-479d-965c-e6ca5e848755.png)

After saying all that, if I have to accept the default (whatever that may be), I guess I'm good.

**Comment by strycore** [comment]
It is highly recommended that you never change the default location of windows games for Lutris. If you want to install on a different drive, choose that initial location when you first add the game to lutris then during the install, always use the default install location. 
This will be particularly important for the upcoming EA App integration.
