### ISSUE TITLE
Lutris/Wine/Proton Updates?

### ISSUE THREAD

**Issue by bicarbonate** [lutris/docs#132]
Apologies for creating an issue about this.. I'm not sure the best place to ask. I saw that there was a new GE Proton version released today and it got me to thinking, what is the process for newer/different Proton versions appearing under the Wine updater menu in Lutris?

**Comment by strycore** [comment]
The current way of updating Wine versions is currently to open the Wine versions dialog and manually download the new version.
Starting from 0.5.14, Lutris will check for new version on startup and download them automatically.
