### ISSUE TITLE
InstallingDrivers.md: Linux Mint bug prevents i386 package downloads from PPA

### ISSUE THREAD

**Issue by dpanter** [lutris/docs#135]
Adding a PPA like Kisak-mesa is currently broken on Linux Mint 21, based on Ubuntu 22.04 LTS (Jammy).
The source list file is added with the condition `arch=amd64` resulting in only amd64 packages being exposed. This in turn results in a broken Mesa installation on the system since you'll get stuck with version mismatches and can't install Kisaks 32-bit Vulkan drivers, among other things.

Removing `arch=amd64` from the source list file allows installing all packages from the PPA and enables a properly working system.
File location: `/etc/apt/sources.list.d/kisak-kisak-mesa-jammy.list`

A bug reports exists. https://github.com/linuxmint/mintsources/issues/242

**Comment by dpanter** [comment]
Mintsources bug fixed, closing this as well.

**Comment by strycore** [comment]
You shouldn't use the Ubuntu PPAs on Linux Mint. Those are for Ubuntu.
