### ISSUE TITLE
EA App - "This game requires permission" - Administrator Privilleges

### ISSUE THREAD

**Issue by intelligentgaming** [lutris/docs#140]
After installing the EA App using Lutris, I successfully signed in with my account and downloaded and installed C&C Red Alert 2. 

On launch, I am greeted by the below. 

![Screenshot from 2023-06-18 11-37-06](https://github.com/lutris/docs/assets/67860954/630639b7-27ed-497c-9ff5-6849a54e4ccd)

And on clicking OK, nothing happens. 

Is there a way to trick the EA App to thinking it is running as an administrator in Lutris?

**Comment by damo901** [comment]
did you ever find a solution to this as im facing it my self on open suse

**Comment by intelligentgaming** [comment]
Unfortunately not.

**Comment by strycore** [comment]
Are you guys using a NTFS partition or something? I have never seen this error in my life.

**Comment by intelligentgaming** [comment]
No, Ext4 using EndeavourOS, EA changed something with the EA App since it does not happen with Origin. It also seems to only happen to games released before UAC with a thing, so pre 2006.

**Comment by tannisroot** [comment]
I recall Origin having a similar issue in its update process, it was definitely not limited to NTFS.
The new app probably has the same coders so it may have popped up again.

**Comment by mirocw** [comment]
yep, exactly the same issue on Linux Mint 21.2 Cinnamon. Installation went fine, but when I try to run a game, it asks for admin privileges, and when you click "OK", it gives error.
So I guess that you need to "trick" somehow EA app for admin privileges, but I don't know how to do that

**Comment by mirocw** [comment]
What if we can add some parameters in a "Advanced launch options", something that will trigger admin privileges?
Talking like a noob, because I am a noob :) 
![Screenshot from 2023-08-18 09-49-51](https://github.com/lutris/docs/assets/107131525/f61e0c99-2c5e-4f07-bf4a-8ac025cdc6ff)

**Comment by strycore** [comment]
I know you guys don't like to give specifics about what games don't run on Lutris but on my end here are some games that run without issue on EA App:
- Apex Legends
- Battlefield 1
- Battlefield 3
- Battlefield V
- Battlefield Hardline
- Crysis 3 Remastered
- Need for Speed
- Need for Speed Heat
- Need for Speed Payback
- Need for Speed Rivals
- Star Wars Battlefront
- Star Wars Jedi: Fallen Order
- Star Wars Squadrons

Despite your efforts to be vague about the game not running, your screenshots clearly leak some information and it appears that Red Alert 2 Yuri's Revenge is the game causing that issue.
Sadly, it seems that EA has removed references to that game from their store. 

I did run into some issue running Command and Conquer Remastered Collection. But I'm not seeing any error about admin access, the game just won't launch.

**Comment by intelligentgaming** [comment]
I think at this stage, it is kind of a lost cause since EA has removed the Ultimate Collection, which was the only way to play the older C&C games that are not on Steam. 

I'll close this thread.

**Comment by strycore** [comment]
I managed to find Red Alert 2 after all (after looking up on cncnet.org). It is included with the C&C Ultimate Collection, which I have access to with EA Play. Let me try it out.

**Comment by strycore** [comment]
I'm getting this on my end: 
![image](https://github.com/lutris/docs/assets/280336/9c438529-2bb6-4520-a5eb-22ef6936b776)


Maybe the glitched message box is the same error about admin permission but I'm unable to see it?

**Comment by strycore** [comment]
I managed to get the error message using a virtual desktop. When I click OK, it says the game has failed to launch due to an error on EA's end

![image](https://github.com/lutris/docs/assets/280336/a322f19a-a3ee-4a95-9908-5a8ada1ffd2a)


![image](https://github.com/lutris/docs/assets/280336/99912785-fa08-49ec-95c9-d8b4a7e29966)

**Comment by strycore** [comment]
This is not a Lutris or Wine issue: https://answers.ea.com/t5/EA-Services-General-Questions/Hold-up-this-game-needs-permissions/td-p/12235545

**Comment by strycore** [comment]
On the EA forums they say the solution is to *remove* administrative rights from the game. Sadly, everything in Wine is run with admin privileges and to my knowledge there is no way to change that.

**Comment by strycore** [comment]
Command and Conquer now work with the latest wine-ge!

**Comment by mirocw** [comment]
> Command and Conquer games now work with the latest wine-ge!

Awesome! I can confirm It's working with wine-ge-8-17. Of course, in case of the black screen menu you need cnc-ddraw from https://github.com/FunkyFr3sh/cnc-ddraw
@intelligentgaming I think It's time for a new YouTube tutorial now? :)

**Comment by intelligentgaming** [comment]
That is great news, I'll see what I can do.

**Comment by strycore** [comment]
What's interesting is that `lutris-GE-Proton8-15` built on Ubuntu 18.04 couldn't launch C&C games, while the same version built on Debian 12 could launch them.

I wonder if our change of OS for our Wine builds has other side effects...
