### ISSUE TITLE
[KALI] AttributeError: 'NoneType' object has no attribute 'people'

### ISSUE THREAD

**Issue by pamuiafrika** [lutris/docs#145]
Following error is displayed:
 sudo add-apt-repository ppa:graphics-drivers/ppa

[sudo] password for pamuiafrika: 
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

Launchpad is already installed

**Comment by thundernet8** [comment]
try
```
apt get install python3-launchpadlib -y
```

**Comment by etoyz** [comment]
> try
> 
> ```
> apt get install python3-launchpadlib -y
> ```

```
apt-get install python3-launchpadlib -y
```

**Comment by strycore** [comment]
Kali Linux is based on Debian, not Ubuntu. Do not use Ubuntu PPAs on Debian.

Also, using Kali Linux as a gaming OS is highly discouraged.

**Comment by charlesvill** [comment]
> Kali Linux is based on Debian, not Ubuntu. Do not use Ubuntu PPAs on Debian.
> 
> Also, using Kali Linux as a gaming OS is highly discouraged.

it's a dependency that was missing fixed by the comment above. At the end of the day they're all Debian lol

**Comment by stealthman22** [comment]
> > Kali Linux is based on Debian, not Ubuntu. Do not use Ubuntu PPAs on Debian.
> > Also, using Kali Linux as a gaming OS is highly discouraged.
> 
> it's a dependency that was missing fixed by the comment above. At the end of the day they're all Debian lol

That's the best response lol.
Kali is based on Debian, Ubuntu is based on Debian. What's the fuss tbvh. 
Kali is Linux, I can do whatever I choose to do with it.
It's not as crazy as we all make it out to be

**Comment by strycore** [comment]
You can use Kali to run Lutris if that's what you want. What you can't get is support from the Lutris development team. I'm sure as hell not gonna install Kali to help you troubleshoot your lutris issues, if you're on Kali, you're expected to have leet hacker skills and be able to support yourself without needing help from anyone. Kali is for the best of the best.
