### ISSUE TITLE
Origin error code 20:403

### ISSUE THREAD

**Issue by mmarusiak** [lutris/docs#148]
I'm getting Origin error code 20:403 all the time. I've tried these Wine versions:
![image](https://github.com/lutris/docs/assets/20907620/4bbb467f-00d0-40ef-ba53-4c5391d6599e)

Some of them are not compatible with Wine ESync, so I was getting error/warning message, but these versions which were compatible with ESync (f.e. Wine 8.0.2), was encountering error code 20:403 when launching origin.

![originerror](https://github.com/lutris/docs/assets/20907620/bd830c74-620b-4afc-8329-3c24226403fc)

I've no idea what can I do to fix it. I'm using Ubuntu 20.04.6 LTS.

**Comment by n3rdcom** [comment]
I think it's because EA has pulled support for Origin in favor of the EA app. We'll need a new source setup in Lutris for the new platform.

**Comment by mmarusiak** [comment]
@n3rdcom I just looked up EA App, and funny enough lutris has already support for that [here](https://lutris.net/games/ea-app/).
It runs perfectly, so I think I'll close the issue, I totally forgot about EA App. Anyway thanks!

**Comment by mmarusiak** [comment]
I think it's just a bit confusing because on main/landing page I could see Steam, Origin and Blizzard Net launchers on left bar instead of EA Play.

**Comment by strycore** [comment]
We now have a working integration with EA App in Lutris. It will be released when 0.5.14 comes out.

**Comment by VladislavNekto** [comment]
> @n3rdcom I just looked up EA App, and funny enough lutris has already support for that [here](https://lutris.net/games/ea-app/). It runs perfectly, so I think I'll close the issue, I totally forgot about EA App. Anyway thanks!

It's broken, i click "close" and installation aborting, but EA Apps seams like installed fine

**Comment by Milor123** [comment]
Some

> @n3rdcom I just looked up EA App, and funny enough lutris has already support for that [here](https://lutris.net/games/ea-app/). It runs perfectly, so I think I'll close the issue, I totally forgot about EA App. Anyway thanks!

It not work for me in my AMD RX 6750 XT And ubuntu 22.04, now work on lutris neither work in bottles, what could i do ?
