### ISSUE TITLE
Recommended Wine build doesn't actually exist

### ISSUE THREAD

**Issue by realnc** [lutris/docs#152]
I had no idea which version of Wine to install in Lutris. After a lot of searching, I found this document:

https://github.com/lutris/docs/blob/master/WineBuilds.md

Which says:

> Lutris uses Wine-GE-Proton as the default Wine build. https://github.com/GloriousEggroll/wine-ge-custom You can use other wine builds at your own risk.

However, there is no such build. There's `wine-ge` and `lutris-GE-Proton`, but there is no `Wine-GE-Proton`.

The above URL leads to the `wine-ge-custom` Github project. Needless to say, `wine-ge-custom` also doesn't exist in Lutris as a Wine build download option.

**Comment by strycore** [comment]
They are all the same thing.

**Comment by realnc** [comment]
> They are all the same thing.

Thanks.
