### ISSUE TITLE
arial32.exe 404 not found

### ISSUE THREAD

**Issue by badpenguin** [lutris/docs#154]
Can't install battle.net
the script hangs when trying to download corefonts from a non working URL
Downloading https://mirrors.kernel.org/gentoo/distfiles/arial32.exe 
return 404
then it hang the script

**Comment by strycore** [comment]
Lutris should download an updated version of Winetricks on startup with the correct URL. I don't know how you haven't got that yet (are you using system winetricks? you should not.....)
