### ISSUE TITLE
Battle.net Login not working even after adding WINE_SIMULATE_WRITECOPY=1 Arch Linux

### ISSUE THREAD

**Issue by xsghetti** [lutris/docs#155]
installer runs fine, when i attempt to login it detects my authenticator and then gives the login error.

**Comment by strycore** [comment]
WINE_SIMULATE_WRITECOPY=1 isn't needed anymore, make sure you're using the latest Wine-GE

**Comment by xsghetti** [comment]
> WINE_SIMULATE_WRITECOPY=1 isn't needed anymore, make sure you're using the latest Wine-GE

I can login, but am unable to connect to internet on battle.net

**Comment by strycore** [comment]
then it's a different issue. Check our wiki page for Battle.net: https://github.com/lutris/docs/blob/master/Battle.Net.md

**Comment by xsghetti** [comment]
no luck still
