### ISSUE TITLE
InstallingDrivers.md has some potentially outdated references in the Fedora section

### ISSUE THREAD

**Issue by AndyMissed** [lutris/docs#159]
I am running Fedora 39, and I was trying to follow the guide and ran into issues trying to make sense of this piece of text:

> "...and open the software app. Click *Add-ons> Hardware Drivers> NVIDIA Linux Graphics Driver> Install*."

I could not for the life of me find this set of navigation instructions on the Software app, so there may have either been an update that changed how the Software app works, or it only works on Fedora instances that are not in a GNOME desktop environment (Because I am).

What ended up working for me is typing these in the command line:

`sudo dnf install akmod-nvidia`
`sudo dnf install xorg-x11-drv-nvidia-cuda`

Which I found buried in the RPMFusion Guide which is linked after saying:

> "If you’re using an older GPU or plan to use multiple GPUs..."

Which was confusing to me as I have a GeForce GTX 1070.

**Comment by strycore** [comment]
Thanks, I have removed the outdated information
