### ISSUE TITLE
`mesa_glthread` performance impact link 404

### ISSUE THREAD

**Issue by Chopper1337** [lutris/docs#163]
In Performance-Tweaks.md, the following link is broken:
[Performance impact of Mesa_glthread](https://www.gamingonlinux.com/wiki/Performance_impact_of_Mesa_glthread)

https://github.com/lutris/docs/blob/5b7a99f14a918892503419701bda286bc701b78e/Performance-Tweaks.md?plain=1#L35

I couldn't find one to replace it with either

**Comment by strycore** [comment]
There is no need to replace it with anything, it's likely obsolete. I removed the link
