### ISSUE TITLE
Xdefiant poor performance, high fps

### ISSUE THREAD

**Issue by loddi-o** [lutris/docs#165]
SYSTEM:

OS: Debian GNU/Linux trixie trixie/sid x86_64
Ryzen 5 5600x, 3070ti Driver Version: 535.183.01 .
GNOME X11. dual monitor configuration, i applied the "[patch](https://www.reddit.com/r/linuxhardware/comments/mht7kn/workaround_for_multiple_monitors_with_different/)" to make mismatched refresh rate work:

> DP-0 connected 900x1440+0+0 right (normal left inverted right x axis y axis) 408mm x 255mm
> DP-2 connected primary 2560x1440+900+0 (normal left inverted right x axis y axis) 698mm x 393mm

WHAT I WANT TO DO:

_I want to play xdefiant on debian._ 

WHAT I DID:

I followed a couple of guides ( https://www.reddit.com/r/linux_gaming/comments/1cyl7us/guide_to_make_xdefiant_work_without_issues_no/ and https://www.youtube.com/watch?v=W3r3ztey-Jg ). 

I even tried bottles, but both methods lead to the same result

**_The game runs fine, I monitored the performances with mangoHUD, and they seem very good, with high and stable fps. However, the game doesn't feel right. The overall feeling is a mix of low fps and stuttering that makes the game almost unplayable_**.

I tried with messing around with in game video settings, but nothing worked.
Other games run fine.

If anyone have an idea of how to make it work or has the same issue, please feel free to share.

**Comment by strycore** [comment]
Do you have the frametime graph on Mangohud? It should be as flat as possible, with no spikes like on the screen below

![Screenshot_20240717_002409](https://github.com/user-attachments/assets/f7b132dc-fb6d-4ea9-98e9-e5bc02ded8e6)

**Comment by loddi-o** [comment]
> Do you have the frametime graph on Mangohud? It should be as flat as possible, with no spikes like on the screen below
> 
> ![Screenshot_20240717_002409](https://private-user-images.githubusercontent.com/280336/349402768-f7b132dc-fb6d-4ea9-98e9-e5bc02ded8e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjE0OTMsIm5iZiI6MTcyMTkyMTE5MywicGF0aCI6Ii8yODAzMzYvMzQ5NDAyNzY4LWY3YjEzMmRjLWZiNmQtNGVhOS05OGU5LWU1YmMwMmRlZDhlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNTI2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmU2OWY2MjRiZTJiMDQzMmZkOTkwM2QzMDFkMjM5YzkyYmJjNzVlMDMxMDIxZWZlODc1M2E4NDA4MzZiZDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i6MUYJD5CsH9uGXlmoa1p_Vez1YpdbpZkxSpt62otfI)

Yes the frametime is flat.

The issue is VRR on multimonitor not working on Nvidia gpus. If you know any solution please feel free to share it

**Comment by strycore** [comment]
Step 1 would likely be using Wayland on KDE. Debian Sid should provide recent enough packages.

**Comment by loddi-o** [comment]
> Step 1 would likely be using Wayland on KDE. Debian Sid should provide recent enough packages.

I... don't know hot to thank you. I just installed fedora 40 KDE, works like a charm.
