### ISSUE TITLE
Fonts are rendered as square blocks in a game window

### ISSUE THREAD

**Issue by chandujr** [lutris/docs#174]
I installed SP Football Life 2025 following the guide here: https://github.com/eskay993/gamefiles/tree/main/sp-football-life-2025

The game installed properly but when I open the game's Settings window using the "Run EXE inside the Wine prefix" option, the window is rendered in all blocks:

![image](https://github.com/user-attachments/assets/394492ed-cd48-4554-8c5f-1b2822181afa)

Is it because of missing fonts? I have all these fonts inside the Fonts directory of the game:
![image](https://github.com/user-attachments/assets/b994072c-b1fb-4619-8c90-e8ee99a7f5d8)

How can I fix this?

Lutris: 0.5.17
OS: Nobara Linux 40

**Comment by strycore** [comment]
Wrong repo, please use Discord or the forums for support questions
