### ISSUE TITLE
Click on Play and nothing happens Origin

### ISSUE THREAD

**Issue by Rickjaconero** [lutris/docs#20]
I tried to play two games, FIFA 20 and SimCity and both I click on play, the save have sync normally then the game doesn't start.

Sorry for bad english

**Comment by g0rge** [comment]
Having a similar issue with command and conquer, it runs...screen hangs, i switch to another application to get out of it...see an instruction error or some such and thats that lol...ah well...someday :)

**Comment by luisdiaz1997** [comment]
I have the same problem too

**Comment by GlennSchner** [comment]
Why was this issue closed with no solution listed? I'm having the same problem.

**Comment by g0rge** [comment]
I'd assume for lack of detail in issue description but when I was trying to use lutris for that software title the error code closed so fast I couldn't see it personally.

**Comment by luisdiaz1997** [comment]
This shouldn't be closed if not solved.... I think
