### ISSUE TITLE
Updated Manjaro Specific Documentation

### ISSUE THREAD

**Issue by frpenguin** [lutris/docs#22]
In the Manjaro Forums I took the liberty of creating a Lutris Guide specific for Manjaro and made changes according to forum members' comments:

https://forum.manjaro.org/t/manjaro-specific-lutris-install-guide/143943/

Please feel free to use it to update your own documentation, or comment on it.

**Comment by Hungry-123** [comment]
The forum doesn't exist

**Comment by Rubo3** [comment]
As far as I remember, the old forum has been replaced with a new one and its content has been archived. I think the guide linked by @frpenguin is [this](https://archived.forum.manjaro.org/t/manjaro-specific-lutris-install-guide/143943).

**Comment by strycore** [comment]
Well now the archive is offline too. 
I've installed Lutris on Manjaro. Afaik, there is no need for extra documentation.
