### ISSUE TITLE
clarify purpose of lutrix-fshack wine versions under WineBuilds.md

### ISSUE THREAD

**Issue by ndroftheline** [lutris/docs#23]
Hey all, 

It appears that the WineBuilds.md page https://github.com/lutris/docs/blob/master/WineBuilds.md doesn't make any mention of the lutrix-fshack.x.y-z options under "Manage wine versions" in the Lutris UI; a brief description would be most welcome.

Thanks for the great project!

~Micah

**Comment by tannisroot** [comment]
Fixed
