### ISSUE TITLE
Update Battle.net documentation for Fedora: Additional dependencies

### ISSUE THREAD

**Issue by izaxone** [lutris/docs#24]
The instructions for installing dependencies on Fedora only show 64 bit packages (with the exception of sqlite, which has both). 

[lutris / docs / Battle.Net.md](https://github.com/lutris/docs/blob/master/Battle.Net.md)

**Current text:** Fedora:`gnutls gnutls-devel openldap openldap-devel libgpg-error sqlite2.i686 sqlite2.x86_64` (Both i686 and x86_64 versions)

**Proposed change:** Fedora: `gnutls.i686 gnutls.x86_64 gnutls-devel.i686 gnutls-devel.x86_64 openldap.i686 openldap.x86_64 openldap-devel.i686 openldap-devel.x86_64 libgpg-error sqlite2.i686 sqlite2.x86_64` (Both i686 and x86_64 versions)

**Comment by dedeoglumrt** [comment]
fedora 32 mouse and system freezing while battle net running and downloading games.
how can i resolve this problem?
thank you

**Comment by Limero** [comment]
The x86_64 and devel packages shouldn't be needed at all. I have gone through all the dependencies and these are the ones needed for me to get everything working on Fedora 33. https://github.com/lutris/docs/pull/39
