### ISSUE TITLE
Following the instructions for installing drivers leads to the OS stopping initializing correctly. 

### ISSUE THREAD

**Issue by heniotierra** [lutris/docs#31]
I followed the instructions in https://github.com/lutris/docs/blob/master/InstallingDrivers.md , and this led to my Mint 19.3 64bit  OS  stopping fully initializing. My computer is an Acer Aspire 7, which comes with a Geforce GTX 1050 TI, so it is Vulkan-capable. 

To be more clear, upon the OS restart, the video card driver won't be loaded anymore, so I get a blank screen, and the OS won't reach the login screen. Maybe this is not the best place to look for help on this, but I thought I'd leave a message here in any case, since the instructions were found here.

**Comment by tannisroot** [comment]
Yeah, really sorry about that, seems like Mint is doing something different and it's breaking systems if you install the proprietary driver. I suggest to either look up the Mint specific way of installing drivers or switch to Ubuntu.

**Comment by tannisroot** [comment]
I've changed the guide based on your report.
