### ISSUE TITLE
Cookies are disabled error

### ISSUE THREAD

**Issue by ghost** [lutris/docs#45]
Hello! In the recent install script I get in the end on the login window the message that cookies are disabled. Login is not possible. During installation in the step "dont try to login because lutris will close the window automatically". The window never was closed, so I closed it manually. Gecko was installed when I first launched the app.

``uname -r > 5.8.18-1-MANJARO``

**Comment by kevinabstract** [comment]
same issue on manjaro unfortunately. :(
