### ISSUE TITLE
Black Screen when loading the game from battle.net launcher

### ISSUE THREAD

**Issue by foranpower** [lutris/docs#47]
After clicking on play world of warcraft from the battle.net launcher a black screen appears with the world of Warcraft glove cursor. The glove cursor disappears after about 2 seconds.

The suggested fix is disable streaming mode. Streaming mode does not appear as a setting as it used to in battle.net WoW setting options.

So, if you have time to help get this to work, that would be appreciated.

**Comment by Deava0** [comment]
I'm having this same issue too

did you get it fixed by any chance ?

**Comment by foranpower** [comment]
I reinstalled linux. Then reinstalled following this video. https://www.youtube.com/watch?v=z-svpE23Pe4&t=2s

It worked. I'm guessing I installed an incorrect driver.
