### ISSUE TITLE
Getting held packages error when following wine guide

### ISSUE THREAD

**Issue by storluffarn** [lutris/docs#5]
I followed the wine guide (https://github.com/lutris/lutris/wiki/Wine-Dependencies) step by step (I'm on ubuntu 18.04 btw), but when I did 

`sudo apt-get install --install-recommends winehq-stable`

then I got `The following packages have unmet dependencies`, just like it says i the guide you might. So I followed up with 

`sudo apt-get install --install-recommends winehq-stable wine-stable wine-stable-i386 wine-stable-amd64`

and 

`sudo apt-get install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386`

as the guide suggests. And now all seems to be fundamentally broken. I tried removing all packages and start over to the best of my abilities, but regardless of what I try I now always get 

```
The following packages have unmet dependencies:
 wine-stable : Depends: wine-stable-i386 (= 5.0.0~bionic)
               Depends: wine-stable-amd64 (= 5.0.0~bionic) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Any suggestions?

edit: typos

**Comment by tannisroot** [comment]
I updated the guide, this won't be an issue anymore.

**Comment by bevinhex** [comment]
I confirm, installing libfaudio (in some way) , fixes the error and get wine installed, wouldn't notice it with apt, aptitude printed out about libfaudio. Thanks.
