### ISSUE TITLE
InstallingDrivers.md comet lake

### ISSUE THREAD

**Issue by samweisgamdschie** [lutris/docs#77]
Hi!
I wondered how the vulkan support of my comet lake IGD of my hp elitebook 840 G7 is? It was not mentioned in the InstallingDrivers.md.. may you provide this information for an linux gaming newb? I have to say, I try to run D2R on it, but still without success (first tried on opensuse tumbleweed, and now with a fresh installation of kde neon). I always run into the black screen behavior no matter what I do.

**Comment by tannisroot** [comment]
Skylake or anything older (including Comet Lake) should support Vulkan fully.
You should try following the Intel section of the guide for Ubuntu based systems, it installs a repository that contains an up-to-date version of mesa, the driver that Intel graphics use on Linux.

**Comment by tannisroot** [comment]
I've updated the docs to make things clearer. Would love to help getting the game to work but I don't own it unfortunately. You should try our discord, maybe people there can help.
