### ISSUE TITLE
Origin will not complete install

### ISSUE THREAD

**Issue by BadLuq** [lutris/docs#90]
Lutris runs through the process, origin opens, let's me log in, and runs fine. however lutris continues to run in the backround and will never complete. Just repeating message as follows:

0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
030c:fixme:netprofm:list_manager_GetConnectivity 00A49DB0, 0090BCD4

I can't find any documentation for this so guidance requested. thank you.

**Comment by Clemenk** [comment]
Hi,

After you've successfully logged in to your origin account, you can close origin and the installer will complete.

**Comment by TobiTenno** [comment]
for a note, due to origin often keeping the tray icon open, wait for the full origin launch, then exit from the menu, as the tray icon will not always be closable

**Comment by padge01** [comment]
> for a note, due to origin often keeping the tray icon open, wait for the full origin launch, then exit from the menu, as the tray icon will not always be closable

This fixed the issue for me.

**Comment by TobiTenno** [comment]
I still couldn't play anything from it, but i'm glad you could install!

**Comment by strycore** [comment]
Closing this since Origin no longer exists and EA App works fine.
