### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by RealPlatinum69** [lutris/docs#91]
What commands do I use to uninstall the drivers?

**Comment by BodilessSleeper** [comment]
Mostly the same commands with different flags ie. whatever you installed on Arch with `sudo pacman -S ...` you should now uninstall with `sudo pacman -R ...`, so look up the specific flags for your package manager (like `sudo apt remove` for Debian based distros and `sudo dnf remove` for Fedora)
Keep in mind that uninstalling the drivers is something you probably don't wanna do unless you installed the wrong ones

**Comment by strycore** [comment]
If you used a PPA, then use ppa-purge. 
For example if you used the kisak PPA:

```
sudo apt install ppa-purge
sudo ppa-purge ppa:kisak/kisak-mesa
```
