### ISSUE TITLE
InstallingDrivers.md: Command to install nvidia-specific tools fails

### ISSUE THREAD

**Issue by 1Maxnet1** [lutris/docs#94]
When I run the mentioned command for nvidia "Proprietary driver and support for Vulkan", it fails on a non-existing package "nvidia-settings". Can I just leave it out or do I need to replace it with another package? If so could you please update the information in the documentation accordingly?

I'm on an up-to-date Manjaro install.

Thanks in regard

**Comment by BodilessSleeper** [comment]
With a bit of searching online I've found [this](https://forum.manjaro.org/t/cant-install-nvidia-settings/78390) post which explains that nvidia-settings get installed with the drivers on Manjaro
This info probably should be in the guide though, probably as a warning or something like that

**Comment by 1Maxnet1** [comment]
Thanks for the clarification.I will prepare and Pull Request and submit it to note that in the guide.
