### ISSUE TITLE
Can't install Origin 

### ISSUE THREAD

**Issue by Anemic18** [lutris/docs#95]
New to Linux.  Can't install Origin 

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

All dependency's met except  "Couldn't find any package whose name or description matched "libldap-2.4-2:i386" on aptitude

[Lutris installer logs.txt](https://github.com/lutris/docs/files/8646092/Lutris.installer.logs.txt)

Sorry for my newbiness. I tried my best ;-;

**Comment by mfinelli** [comment]
On Ubuntu 22.04 Jammy the libldap package is `libldap-2.5-0` (so you should apt install `libldap-2.5-0:i386`): https://packages.ubuntu.com/jammy/libldap-2.5-0

**Comment by strycore** [comment]
Closing this since Origin no longer exists and EA App installs and runs fine.
